package org.example.interfaces.mappers;

import org.example.domain.dto.request.CreateUserRequest;
import org.example.domain.dto.response.CreateUserResponse;
import org.example.domain.model.UserModel;
import java.time.LocalDateTime;

public class UserDtoMapper {

    public CreateUserResponse toResponse(UserModel domainObject) {
        return new CreateUserResponse(
                domainObject.id(),
                domainObject.username(),
                domainObject.email(),
                domainObject.role(),
                domainObject.createdAt(),
                domainObject.updatedAt()
        );
    }

    public UserModel toDomain(CreateUserRequest request) {
        return new UserModel(
                null,              // id will be generated by the database
                request.getUsername(),
                request.getEmail(),
                request.getRole() != null ? request.getRole() : "USER", // Default role if not provided
                null,              // passwordHash will be set after encoding
                null,              // createdAt will be set by Hibernate
                null               // updatedAt will be set by Hibernate
        );
    }
}