# Database Configuration with Environment Variables
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
# HikariCP Configuration (optional but recommended)
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5


huggingface.api.token=${HF_API_TOKEN}